/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 computer.gltf --transform 
Files: computer.gltf [2.61MB] > computer-transformed.glb [223.98KB] (91%)
Author: Tyler P Halterman (https://sketchfab.com/tylerhalterman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desktop-computer-561abc2fc95941609fc7bc6f232895c2
Title: Desktop Computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Computer(props) {
  const { nodes, materials } = useGLTF('../src/data/3d/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['01___Default']} scale={0.501} />
    </group>
  )
}

useGLTF.preload('../src/data/3d/computer-transformed.glb')
